apiVersion: v2
name: vaultwarden
description: vaultwarden is an unofficial Bitwarden-compatible server written in Rust
icon: https://helm.sh/img/helm.svg
type: application
keywords:
  - Rust
  - vaultwarden
sources:
  - https://github.com/hatchertechnology/charts
  - https://github.com/dani-garcia/vaultwarden
appVersion: 1.30.3
maintainers:
  - name: KerryHatcher
    email: kerry@kerryhatcher.com
    url: https://www.kerryhatcher.com
version: 0.22.7
kubeVersion: ">=1.12.0-0"
